# Generated by Django 5.0.1 on 2024-05-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpinghands', '0004_rename_volunteerrmark_donation_volunteerremark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonationArea',
            new_name='Organization',
        ),
    ]
