# Generated by Django 5.0.1 on 2024-05-19 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpinghands', '0006_organization_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.CharField(default=False, max_length=10)),
                ('donationarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpinghands.organization')),
            ],
        ),
    ]
