# Generated by Django 5.0.1 on 2024-05-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpinghands', '0007_paymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='paid',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
