# Generated by Django 5.0.1 on 2024-05-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpinghands', '0008_alter_paymentdetails_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='payment_id',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
