# Generated by Django 5.0.1 on 2024-05-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpinghands', '0009_rename_payment_id_paymentdetails_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='order_id',
            new_name='transaction_id',
        ),
    ]
